# Generated by Django 5.0.4 on 2024-05-12 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AgeRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DaySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.PositiveIntegerField(blank=True, null=True)),
                ('end_year', models.PositiveIntegerField(blank=True, null=True)),
                ('job_place', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('one_time_price', models.DecimalField(decimal_places=2, default=None, max_digits=10)),
                ('recurring_price', models.DecimalField(decimal_places=2, default=None, max_digits=10)),
                ('dmn_about', models.CharField(blank=True, max_length=300, null=True)),
                ('years_of_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('additional_services', models.ManyToManyField(to='myNannyApplication.additionalservice')),
                ('age_ranges', models.ManyToManyField(blank=True, to='myNannyApplication.agerange')),
                ('schedules', models.ManyToManyField(blank=True, to='myNannyApplication.dayschedule')),
                ('pet_types', models.ManyToManyField(blank=True, to='myNannyApplication.pettype')),
                ('services', models.ManyToManyField(to='myNannyApplication.service')),
                ('work_experiences', models.ManyToManyField(blank=True, to='myNannyApplication.workexperience')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(default='Organization', max_length=100)),
                ('organisation_url', models.URLField(blank=True, null=True)),
                ('organisation_name', models.CharField(blank=True, max_length=100, null=True)),
                ('refrence1_name', models.CharField(blank=True, max_length=100, null=True)),
                ('refrence2_name', models.CharField(blank=True, max_length=100, null=True)),
                ('refrence1_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('refrence2_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField(default=False)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('no_of_child', models.PositiveIntegerField(default=0)),
                ('display_name', models.CharField(blank=True, max_length=150, null=True)),
                ('general_about', models.TextField(blank=True, default=None, max_length=400, null=True)),
                ('domains', models.ManyToManyField(blank=True, to='myNannyApplication.domain')),
                ('languages', models.ManyToManyField(to='myNannyApplication.language')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
