# Generated by Django 5.0.4 on 2024-05-12 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myNannyApplication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='increment',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
