# Generated by Django 5.0.4 on 2024-05-12 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myNannyApplication', '0002_domain_increment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='no_of_child',
        ),
        migrations.AddField(
            model_name='domain',
            name='no_of_child',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
