# Generated by Django 5.0.4 on 2024-05-12 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myNannyApplication', '0003_remove_profile_no_of_child_domain_no_of_child'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domain',
            old_name='dmn_about',
            new_name='domin_about',
        ),
    ]
