# Generated by Django 5.0.4 on 2024-05-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myNannyApplication', '0004_rename_dmn_about_domain_domin_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address_proof',
            field=models.ImageField(blank=True, null=True, upload_to='verification/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='driving_license_proof',
            field=models.ImageField(blank=True, null=True, upload_to='verification/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='police_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='verification/'),
        ),
    ]
