# Generated by Django 5.0.4 on 2024-05-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myNannyApplication', '0005_profile_address_proof_profile_driving_license_proof_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address_proof',
            field=models.ImageField(blank=True, null=True, upload_to='verification/address_proof'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='driving_license_proof',
            field=models.ImageField(blank=True, null=True, upload_to='verification/dlp'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='police_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='verification/police_certificate'),
        ),
    ]
