# Generated by Django 4.2.7 on 2024-05-20 19:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myNannyApplication', '0006_alter_profile_address_proof_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='domains',
        ),
        migrations.AddField(
            model_name='profile',
            name='domains',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
    ]
