# Generated by Django 4.2.7 on 2024-05-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myNannyApplication', '0007_remove_profile_domains_profile_domains'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='domains',
            field=models.TextField(blank=True, null=True),
        ),
    ]
