# Generated by Django 5.0.4 on 2024-05-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myNannyApplication', '0011_rename_refrence1_name_profile_reference1_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='address_proof',
            new_name='identity_proof',
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
