# Generated by Django 5.0.4 on 2024-05-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blog_content_alter_blog_post_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='post_type',
            field=models.CharField(choices=[('Tips', 'Tips'), ('Advice', 'Advice'), ('General', 'General')], default='Tips', max_length=10),
        ),
    ]
